apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-broker
  labels:
    io.kompose.service: broker
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.type }}
  selector:
    io.kompose.service: broker
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.broker.ports | toYaml | nindent 2 }}