apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" . }}-postgres-pvc
  labels:
    app: postgres
    type: local
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-postgres-pvc
  labels:
    app: postgres
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvc.storageClass | quote }}