apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-postgres
  labels:
    io.kompose.service: postgres
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    io.kompose.service: postgres
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgres.ports | toYaml | nindent 2 }}