apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-server
  labels:
    io.kompose.service: server
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "mychart.fullname" . }}-server'
            port:
              number: 8080
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-server
  labels:
    io.kompose.service: server
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  selector:
    io.kompose.service: server
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.server.ports | toYaml | nindent 2 }}