broker:
  broker:
    image:
      repository: redis
      tag: 7.0.12
  replicas: 1

keycloak:
  keycloak:
    env:
      dbAddr: keycloak-postgres
      dbPassword: passwd
      dbUser: postgres
      dbVendor: postgres
      keycloakImport: /import/realm.json
      keycloakPassword: kc_pass
      keycloakUser: kc_user
    image:
      repository: keycloak/keycloak
      tag: latest
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  replicas: 1
  type: LoadBalancer


keycloakPostgres:
  ports:
  - name: postgres
    port: 5432
    targetPort: 0
  postgres:
    env:
      pgdata: /var/lib/postgresql/data/pgdata
      postgresDb: keycloak
      postgresPassword: passwd
    image:
      repository: postgres
      tag: "15.3"
  type: ClusterIP
kubernetesClusterDomain: cluster.local

postgres:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  postgres:
    env:
      pgdata: /var/lib/postgresql/data/pgdata
      postgresDb: qunicorn
      postgresPassword: passwd
    image:
      repository: postgres
      tag: "15.3"
  replicas: 1
  type: ClusterIP

pvc:
  postgresPvc:
    storageClass: standard
    storageRequest: 1Gi

server:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  server:
    env:
      brokerUrl: redis://broker:6379
      containerMode: server
      dbUrl: postgresql://postgres:passwd@postgres/qunicorn
      jwksUrl: http://keycloak:8081/auth/realms/qunicorn/protocol/openid-connect/certs
      numbaCacheDir: /app/cache
      serverPort: "8080"
    image:
      repository: iaasgeorgdl/qunicorn
      tag: release.11.23
  type: LoadBalancer

worker:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  replicas: 1
  type: ClusterIP
  worker:
    env:
      brokerUrl: redis://broker:6379
      containerMode: worker
      dbUrl: postgresql://postgres:passwd@postgres/qunicorn
      numbaCacheDir: /app/cache
    image:
      repository: iaasgeorgdl/qunicorn
      tag: release.11.23
