apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8443
      targetPort: 8080
  selector:
    app: keycloak
  type: {{ .Values.keycloak.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.keycloak.image.repository }}
          
          args: ["start-dev","--import-realm"]

          env:
            - name: DB_ADDR
              value: {{ quote .Values.keycloak.keycloak.env.DB_ADDR }}
            - name: DB_DATABASE
              value: {{ quote .Values.keycloak.keycloak.env.DB_DATABASE }}
            - name: DB_PASSWORD
              value: {{ quote .Values.keycloak.keycloak.env.DB_PASSWORD }}
            - name: DB_PORT
              value: {{ quote .Values.keycloak.keycloak.env.DB_PORT }}
            - name: DB_SCHEMA
              value: {{ quote .Values.keycloak.keycloak.env.DB_SCHEMA }}
            - name: DB_USER
              value: {{ quote .Values.keycloak.keycloak.env.DB_USER }}
            - name: DB_VENDOR
              value: {{ quote .Values.keycloak.keycloak.env.DB_VENDOR }}
            - name: KC_HTTP_ENABLED
              value: {{ quote .Values.keycloak.keycloak.env.KC_HTTP_ENABLED }}
            - name: KC_METRICS_ENABLED
              value: {{ quote .Values.keycloak.keycloak.env.KC_METRICS_ENABLED }}
            - name: KC_PROXY_MODE
              value: {{ quote .Values.keycloak.keycloak.env.KC_PROXY_MODE }}
            - name: KEYCLOAK_ADMIN
              value: {{ quote .Values.keycloak.keycloak.env.KEYCLOAK_ADMIN }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ quote .Values.keycloak.keycloak.env.KEYCLOAK_ADMIN_PASSWORD }}
            - name: KEYCLOAK_PASSWORD
              value: {{ quote .Values.keycloak.keycloak.env.KEYCLOAK_PASSWORD }}
            - name: KEYCLOAK_USER
              value: {{ quote .Values.keycloak.keycloak.env.KEYCLOAK_USER }}
          
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - name: keycloak-volume
              mountPath: /import
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-configmap
