apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: worker
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      labels:
        io.kompose.network/qunicorn-core-qunicorn: "true"
        io.kompose.service: worker
    spec:
      containers:
        - env:
            - name: BROKER_URL
              value: {{ quote .Values.worker.worker.env.brokerUrl }}
            - name: CONTAINER_MODE
              value: {{ quote .Values.worker.worker.env.containerMode }}
            - name: DB_URL
              value: {{ quote .Values.worker.worker.env.dbUrl }}
            - name: NUMBA_CACHE_DIR
              value: {{ quote .Values.worker.worker.env.numbaCacheDir }}
          image: {{ .Values.worker.worker.image.repository }}:{{ .Values.worker.worker.image.tag
          | default .Chart.AppVersion }}
          name: worker
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: worker
  name: worker
  namespace: default
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: worker
