broker:
  broker:
    image:
      repository: redis
      tag: 7.2.0
  replicas: 1

keycloak:
  keycloak:
    env:
      DB_ADDR: keycloak_postgres
      DB_DATABASE: keycloak
      DB_PASSWORD: pas443
      DB_PORT: "5432"
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_VENDOR: postg443
      KC_HTTP_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_PROXY_MODE: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_PASSWORD: kc_pass
      KEYCLOAK_USER: kc_user
      
    image:
      repository: quay.io/keycloak/keycloak
      tag: latest
  replicas: 1
  type: LoadBalancer


keycloakPostgres:
  postgres:
    env:
      pgdata: /var/lib/postgresql/data/pgdata
      postgresDb: keycloak
      postgresPassword: passwd
    image:
      repository: postgres
      tag: "15.3"

postgres:
  postgres:
    env:
      pgdata: /var/lib/postgresql/data/pgdata
      postgresDb: qunicorn
      postgresPassword: passwd
    image:
      repository: postgres
      tag: "15.3"
  replicas: 1

pvc:
  postgresPvc:
    storageClass: standard
    storageRequest: 1Gi

server:
  replicas: 1
  server:
    env:
      brokerUrl: redis://broker:6379
      containerMode: server
      dbUrl: postgresql+psycopg://postgres:passwd@postgres/qunicorn
      jwksUrl: http://keycloak:8081/auth/realms/qunicorn/protocol/openid-connect/certs
      numbaCacheDir: /app/cache
      serverPort: "8082"
    image:
      repository: ghcr.io/qunicorn/qunicorn-core
      tag: main
  type: LoadBalancer

worker:
  replicas: 1
  worker:
    env:
      brokerUrl: redis://broker:6379
      containerMode: worker
      dbUrl: postgresql+psycopg://postgres:passwd@postgres/qunicorn
      numbaCacheDir: /app/cache
    image:
      repository: ghcr.io/qunicorn/qunicorn-core
      tag: main
