kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    type: local
    app: postgres
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.pvc.postgresPvc.storageClass | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvc.storageRequest | quote }}
