apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
  type: {{ .Values.keycloakPostgres.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: {{ .Values.keycloakPostgres.postgres.image.repository }}:{{ .Values.keycloakPostgres.postgres.image.tag}}
          name: postgres
          env:
            - name: PGDATA
              value: {{ quote .Values.keycloakPostgres.postgres.env.pgdata }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.keycloakPostgres.postgres.env.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ quote .Values.keycloakPostgres.postgres.env.postgresDb }}
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: keycloak-pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
