apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      labels:
        io.kompose.network/qunicorn-core-qunicorn: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: CONTAINER_MODE
              value: {{ quote .Values.server.server.env.containerMode }}
            - name: BROKER_URL
              value: {{ quote .Values.server.server.env.brokerUrl }}
            - name: JWKS_URL
              value: {{ quote .Values.server.server.env.jwksUrl }}
            - name: DB_URL
              value: {{ quote .Values.server.server.env.dbUrl }}
            - name: SERVER_PORT
              value: {{ quote .Values.server.server.env.serverPort }}
            - name: NUMBA_CACHE_DIR
              value: {{ quote .Values.server.server.env.numbaCacheDir }}
          image: {{ .Values.server.server.image.repository }}:{{ .Values.server.server.image.tag
          | default .Chart.AppVersion }}
          name: server
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: servers
  name: server
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: server
  type: LoadBalancer
